-- PROJECT: E-commerce Business Analytics
-- DATABASE: Oracle SQL

-- Oracle SQL project for practicing analytics queries.



-- CREATING TABLES

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    gender VARCHAR2(10),
    country VARCHAR2(50),
    registration_date DATE NOT NULL
);

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(100) NOT NULL
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category_id NUMBER,
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER NOT NULL,
    CONSTRAINT fk_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    order_date DATE NOT NULL,
    order_status VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER,
    product_id NUMBER,
    quantity NUMBER NOT NULL,
    unit_price NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);


-- INSERT DATA


-- CATEGORIES

INSERT INTO categories (category_name) VALUES ('Electronics');
INSERT INTO categories (category_name) VALUES ('Books');
INSERT INTO categories (category_name) VALUES ('Sports');
INSERT INTO categories (category_name) VALUES ('Home');


-- CUSTOMERS

INSERT INTO customers (first_name, last_name, gender, country, registration_date)
VALUES ('Ali', 'Mammadov', 'Male', 'Azerbaijan', DATE '2023-01-10');

INSERT INTO customers (first_name, last_name, gender, country, registration_date)
VALUES ('Leyla', 'Aliyeva', 'Female', 'Azerbaijan', DATE '2023-02-11');

INSERT INTO customers (first_name, last_name, gender, country, registration_date)
VALUES ('John', 'Smith', 'Male', 'UK', DATE '2023-03-15');

INSERT INTO customers (first_name, last_name, gender, country, registration_date)
VALUES ('Maria', 'Ivanova', 'Female', 'Russia', DATE '2023-04-20');

INSERT INTO customers (first_name, last_name, gender, country, registration_date)
VALUES ('Kenan', 'Hasanov', 'Male', 'Turkey', DATE '2023-05-08');

INSERT INTO customers (first_name, last_name, gender, country, registration_date)
VALUES ('Emma', 'Brown', 'Female', 'USA', DATE '2023-06-14');


-- PRODUCTS

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('iPhone 14', 1, 1200, 25);

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('Gaming Mouse', 1, 75, 100);

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('SQL for Analysts', 2, 40, 60);

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('Basketball', 3, 35, 80);

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('Office Chair', 4, 210, 15);

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('Monitor 27 inch', 1, 320, 40);

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('Dumbbells Set', 3, 150, 22);

INSERT INTO products (product_name, category_id, price, stock_quantity)
VALUES ('Coffee Table', 4, 180, 12);


-- ORDERS

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (1, DATE '2024-01-05', 'Completed');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (2, DATE '2024-01-10', 'Completed');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (1, DATE '2024-02-01', 'Completed');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (3, DATE '2024-02-11', 'Cancelled');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (4, DATE '2024-02-15', 'Completed');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (5, DATE '2024-03-01', 'Completed');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (6, DATE '2024-03-10', 'Completed');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (2, DATE '2024-03-18', 'Completed');

INSERT INTO orders (customer_id, order_date, order_status)
VALUES (3, DATE '2024-03-25', 'Completed');


-- ORDER ITEMS

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (1, 1, 1, 1200);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (1, 2, 2, 75);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (2, 3, 1, 40);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (2, 4, 2, 35);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (3, 6, 1, 320);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (4, 1, 1, 1200);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (5, 5, 1, 210);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (6, 7, 1, 150);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (7, 8, 1, 180);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (8, 2, 3, 75);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (9, 6, 2, 320);

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (9, 3, 1, 40);



-- TOTAL REVENUE

SELECT
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed';


-- TOTAL COMPLETED ORDERS

SELECT
    COUNT(*) AS completed_orders
FROM orders
WHERE order_status = 'Completed';


-- AVERAGE ORDER VALUE

WITH order_totals AS (
    SELECT
        oi.order_id,
        SUM(oi.quantity * oi.unit_price) AS order_total
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY oi.order_id
)

SELECT
    ROUND(AVG(order_total), 2) AS average_order_value
FROM order_totals;


-- TOP SELLING PRODUCTS

SELECT
    p.product_name,
    SUM(oi.quantity) AS units_sold,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY units_sold DESC;


-- SALES BY CATEGORY

SELECT
    c.category_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_sales
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_sales DESC;


-- CUSTOMER LIFETIME VALUE

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS lifetime_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY lifetime_value DESC;


-- MONTHLY SALES TREND

SELECT
    TO_CHAR(o.order_date, 'YYYY-MM') AS sales_month,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY TO_CHAR(o.order_date, 'YYYY-MM')
ORDER BY sales_month;


-- REPEAT CUSTOMERS

SELECT
    c.first_name,
    c.last_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_status = 'Completed'
GROUP BY
    c.first_name,
    c.last_name
HAVING COUNT(o.order_id) > 1;


-- CUSTOMERS WITH NO ORDERS

SELECT
    c.customer_id,
    c.first_name,
    c.last_name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- INVENTORY CHECK

SELECT
    product_name,
    stock_quantity,
    CASE
        WHEN stock_quantity < 20 THEN 'Low Stock'
        WHEN stock_quantity BETWEEN 20 AND 50 THEN 'Medium Stock'
        ELSE 'High Stock'
    END AS stock_level
FROM products
ORDER BY stock_quantity;


-- WINDOW FUNCTION EXAMPLE

WITH daily_sales AS (
    SELECT
        o.order_date,
        SUM(oi.quantity * oi.unit_price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY o.order_date
)

SELECT
    order_date,
    revenue,
    SUM(revenue) OVER (
        ORDER BY order_date
    ) AS cumulative_revenue
FROM daily_sales;


-- RANKING CUSTOMERS

WITH customer_revenue AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        SUM(oi.quantity * oi.unit_price) AS total_spent
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name
)

SELECT
    first_name,
    last_name,
    ROUND(total_spent, 2) AS total_spent,
    RANK() OVER (
        ORDER BY total_spent DESC
    ) AS customer_rank
FROM customer_revenue;


-- STATISTICAL ANALYSIS

SELECT
    ROUND(AVG(price), 2) AS avg_price,
    ROUND(MIN(price), 2) AS min_price,
    ROUND(MAX(price), 2) AS max_price,
    ROUND(STDDEV(price), 2) AS stddev_price
FROM products;


-- CORRELATION ANALYSIS

WITH sales_data AS (
    SELECT
        p.product_id,
        p.price,
        SUM(oi.quantity) AS quantity_sold
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY
        p.product_id,
        p.price
)

SELECT
    ROUND(CORR(price, quantity_sold), 3) AS correlation_result
FROM sales_data;


-- CUSTOMER SEGMENTATION

WITH customer_totals AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        SUM(oi.quantity * oi.unit_price) AS total_spent
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name
)

SELECT
    first_name,
    last_name,
    total_spent,
    CASE
        WHEN total_spent >= 1000 THEN 'VIP'
        WHEN total_spent >= 300 THEN 'Regular'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer_totals
ORDER BY total_spent DESC;


/*
Skills demonstrated in this project:

- Oracle SQL syntax
- relational database design
- joins
- aggregations
- CTEs
- window functions
- ranking functions
- CASE expressions
- KPI calculations
- statistical analysis
- correlation analysis
- business reporting

Possible future improvements:
- views
- procedures
- indexes
*/